target: 8.8.8.8
ping_interval_seconds: 1
retention_minutes: 180
listen_host: 0.0.0.0
listen_port: 8080
data_dir: ./data
thresholds:
    ping_great: 40
    ping_good: 70
    ping_okay: 110
    ping_max: 200
    jitter_great: 8
    jitter_good: 15
    jitter_okay: 30
    jitter_max: 60
    loss_good: 1
    loss_okay: 3
    loss_max: 15
speedtest:
    servers:
        - https://speedtest.selectel.ru/
        - https://nyc.speedtest.clouvider.net/backend/
        - https://fra.speedtest.clouvider.net/backend/
        - https://speedtest.singapore.linode.com/
    download_path: ""
    upload_path: ""
    download_url: ""
    upload_url: ""
    duration_seconds: 10
    parallel_streams: 8
